### ISSUE TITLE
Error messages are not compatible with "rawOutput" option.

### ISSUE THREAD

**Issue by phcoliveira** [ember-bootstrap/ember-bootstrap-changeset-validations#16]
Ember Changeset Validations by default populates an array with strings containing error messages. However, it does not support the option "rawOutput", which uses more flexible objects instead of strings.

**Comment by jelhan** [comment]
Could you elaborate a little bit on your use case? This addon should work as a plugin layer extending the form components provided by Ember Bootstrap (`<BsForm>`) to support validations provided by Ember Changeset Validations. It should be zero config and there shouldn't be a need to interact with the validation errors through this library directly.
